spring:
  application:
    name: persons-app-disco
 server:
   port: 8071
 eureka:
   instance:
     hostname: eurekaserver
   client:
     registerWithEureka: false
     fetchRegistry: false
   serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   server:
     waitTimeInMsWhenSyncEmpty: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
